### ISSUE TITLE
How to build a complete runnable application?

### ISSUE THREAD

**Issue by chhh** [cuba-labs/java-electron-tutorial#1]
The tutorial is awesome and it works. I can run the app from _src\main\electron_ with `npx electron .`
But how do I create a runnable final product, like a separate executable? Running _src\main\electron\demo\bin\demo.bat_ starts an embedded server that is accessible from the browser.
How to achieve the same effect as from `npx electron .` when ran from _src\main\electron_?

**Comment by jreznot** [comment]
Hi!

The application should be packaged with `electron-packager` as it is shown here: https://github.com/jreznot/electron-java-app/blob/master/build.gradle#L147

If you want to see how to build the complete solution then take a loot at the full blown application: https://github.com/jreznot/electron-java-app

**Comment by chhh** [comment]
Thanks!
